export interface HackingChallenge {
  id: number;
  title: string;
  link: string;
  category: "Rooms" | "Challenges";
}

export const hackingChallenges: HackingChallenge[] = [
  { id: 1, title: "Offensive Security Intro", link: "https://tryhackme.com/room/offensivesecurityintro", category: "Rooms" },
  { id: 2, title: "Defensive Security Intro", link: "https://tryhackme.com/room/defensivesecurityintro", category: "Rooms" },
  { id: 3, title: "DNS in detail", link: "https://tryhackme.com/room/dnsindetail", category: "Rooms" },
  { id: 4, title: "How websites work", link: "https://tryhackme.com/room/howwebsiteswork", category: "Rooms" },
  { id: 5, title: "HTTP in detail", link: "https://tryhackme.com/room/httpindetail", category: "Rooms" },
  { id: 6, title: "Putting it all together", link: "https://tryhackme.com/room/puttingitalltogether", category: "Rooms" },
  { id: 7, title: "Linux Fundamentals 1", link: "https://tryhackme.com/room/linuxfundamentalspart1", category: "Rooms" },
  { id: 8, title: "Windows Fundamentals 1", link: "https://tryhackme.com/room/windowsfundamentals1xbx", category: "Rooms" },
  { id: 9, title: "Active Directory Basics", link: "https://tryhackme.com/room/winadbasics", category: "Rooms" },
  { id: 10, title: "Windows Command Line", link: "https://tryhackme.com/room/windowscommandline", category: "Rooms" },
  { id: 11, title: "Networking Concepts", link: "https://tryhackme.com/room/networkingconcepts", category: "Rooms" },
  { id: 12, title: "Cryptography Basics", link: "https://tryhackme.com/room/cryptographybasics", category: "Rooms" },
  { id: 13, title: "Metasploit: Introduction", link: "https://tryhackme.com/room/metasploitintro", category: "Rooms" },
  { id: 14, title: "Web application basics", link: "https://tryhackme.com/room/webapplicationbasics", category: "Rooms" },
  { id: 15, title: "OWASP Top 10 - 2021", link: "https://tryhackme.com/room/owasptop102021", category: "Rooms" },
  { id: 16, title: "Hydra", link: "https://tryhackme.com/room/hydra", category: "Rooms" },
  { id: 17, title: "SOC Fundamentals", link: "https://tryhackme.com/room/socfundamentals", category: "Rooms" },
  { id: 18, title: "Introduction to SIEM", link: "https://tryhackme.com/room/introtosiem", category: "Rooms" },
  { id: 19, title: "Cyberchef: The Basics", link: "https://tryhackme.com/room/cyberchefbasics", category: "Rooms" },
  { id: 20, title: "Security Principles", link: "https://tryhackme.com/room/securityprinciples", category: "Rooms" },
  { id: 21, title: "Pentesting Fundamentals", link: "https://tryhackme.com/room/pentestingfundamentals", category: "Rooms" },
  { id: 22, title: "SQL Fundamentals", link: "https://tryhackme.com/room/sqlfundamentals", category: "Rooms" },
  { id: 23, title: "Passive Recon", link: "https://tryhackme.com/room/passiverecon", category: "Rooms" },
  { id: 24, title: "Active Recon", link: "https://tryhackme.com/room/activerecon", category: "Rooms" },
  { id: 25, title: "Vulnerabilities 101", link: "https://tryhackme.com/room/vulnerabilities101", category: "Rooms" },
  { id: 26, title: "SQL Injection", link: "https://tryhackme.com/room/sqlinjectionlm", category: "Rooms" },
  { id: 27, title: "NMAP live host discovery", link: "https://tryhackme.com/room/nmap01", category: "Rooms" },
  { id: 28, title: "Linux Privilege Escalation", link: "https://tryhackme.com/room/linprivesc", category: "Rooms" },
  { id: 29, title: "Snort", link: "https://tryhackme.com/room/snort", category: "Rooms" },
  { id: 30, title: "Regular Expression", link: "https://tryhackme.com/room/catregex", category: "Rooms" },
  { id: 31, title: "Windows Forensics 1", link: "https://tryhackme.com/room/windowsforensics1", category: "Rooms" },
  { id: 32, title: "Encryption – Crypto 101", link: "https://tryhackme.com/room/encryptioncrypto101", category: "Rooms" },
  { id: 33, title: "Intro to DevSecOps", link: "https://tryhackme.com/room/introductiontodevsecops", category: "Rooms" },
  { id: 34, title: "Red Team OPSEC", link: "https://tryhackme.com/room/opsec", category: "Rooms" },
  { id: 35, title: "Splunk: Exploring SPL", link: "https://tryhackme.com/room/splunkexploringspl", category: "Rooms" },
  { id: 36, title: "Android Hacking 101", link: "https://tryhackme.com/room/androidhacking101", category: "Rooms" },
  { id: 37, title: "Secure Network Architecture", link: "https://tryhackme.com/room/introtosecurityarchitecture", category: "Rooms" },
  { id: 38, title: "Bypassing UAC", link: "https://tryhackme.com/room/bypassinguac", category: "Rooms" },
  { id: 39, title: "Advanced SQL Injection", link: "https://tryhackme.com/room/advancedsqlinjection", category: "Rooms" },
  { id: 40, title: "Server Side Template Injection", link: "https://tryhackme.com/room/learnssti", category: "Rooms" },
  { id: 41, title: "Linux Server Forensics", link: "https://tryhackme.com/room/linuxserverforensics", category: "Rooms" },
  { id: 42, title: "Server-Side Request Forgery", link: "https://tryhackme.com/room/ssrfhr", category: "Rooms" },
  { id: 43, title: "Dumping Router Firmware", link: "https://tryhackme.com/room/rfirmware", category: "Rooms" },
  { id: 44, title: "Introduction to Honeypots", link: "https://tryhackme.com/room/introductiontohoneypots", category: "Rooms" },
  { id: 45, title: "CrossSite Request Forgery", link: "https://tryhackme.com/room/csrfV2", category: "Rooms" },
  { id: 46, title: "Threat Intelligence for SOC", link: "https://tryhackme.com/room/threatintelligenceforsoc", category: "Rooms" },
  { id: 47, title: "Intrusion Detection", link: "https://tryhackme.com/room/idsevasion", category: "Rooms" },
  { id: 48, title: "Incident Response Process", link: "https://tryhackme.com/room/incidentresponseprocess", category: "Rooms" },
  { id: 49, title: "Cyber Kill Chain", link: "https://tryhackme.com/room/cyberkillchain", category: "Rooms" },
  { id: 50, title: "Legal Considerations in DFIR", link: "https://tryhackme.com/room/dfirprocesslegalconsiderations", category: "Rooms" },

  // Challenges
  { id: 51, title: "Intro to Cybersecurity Module 1", link: "https://www.netacad.com/courses/introduction-tocybersecurity?courseLang=en-US#", category: "Challenges" },
  { id: 52, title: "Intro to Cybersecurity Module 2", link: "https://www.netacad.com/courses/introduction-tocybersecurity?courseLang=en-US#", category: "Challenges" },
  { id: 53, title: "Intro to Cybersecurity Module 3", link: "https://www.netacad.com/courses/introduction-tocybersecurity?courseLang=en-US#", category: "Challenges" },
  { id: 54, title: "Intro to Cybersecurity Module 4", link: "https://www.netacad.com/courses/introduction-tocybersecurity?courseLang=en-US#", category: "Challenges" },
  { id: 55, title: "Intro to Cybersecurity Module 5", link: "https://www.netacad.com/courses/introduction-tocybersecurity?courseLang=en-US#", category: "Challenges" },
  { id: 56, title: "Basic Pentesting", link: "https://tryhackme.com/room/basicpentestingjt", category: "Challenges" },
  { id: 57, title: "Pickle Rick", link: "https://tryhackme.com/room/picklerick", category: "Challenges" },
  { id: 58, title: "RootMe", link: "https://tryhackme.com/room/rrootme", category: "Challenges" },
  { id: 59, title: "MrRobot CTF", link: "https://tryhackme.com/room/mrrobot", category: "Challenges" },
  { id: 60, title: "OhSINT", link: "https://tryhackme.com/room/ohsint", category: "Challenges" },
  { id: 61, title: "Simple CTF", link: "https://tryhackme.com/room/easyctf", category: "Challenges" },
  { id: 62, title: "Attacktive Directory", link: "https://tryhackme.com/room/attacktivedirectory", category: "Challenges" },
  { id: 63, title: "Bounty Hacker", link: "https://tryhackme.com/room/cowboyhacker", category: "Challenges" },
  { id: 64, title: "Agent Sudo", link: "https://tryhackme.com/room/agentsudoctf", category: "Challenges" },
  { id: 65, title: "Crack the Hash", link: "https://tryhackme.com/room/crackthehash", category: "Challenges" },
  { id: 66, title: "Investigating Windows", link: "https://tryhackme.com/room/investigatingwindows", category: "Challenges" },
  { id: 67, title: "c4ptur3-th3-fl4g", link: "https://tryhackme.com/room/c4ptur3th3fl4g", category: "Challenges" },
  { id: 68, title: "Lazy Admin", link: "https://tryhackme.com/room/lazyadmin", category: "Challenges" },
  { id: 69, title: "Squid game", link: "https://tryhackme.com/room/squidgameroom", category: "Challenges" },
  { id: 70, title: "Wonderland", link: "https://tryhackme.com/room/wonderland", category: "Challenges" },
  { id: 71, title: "WhyHackMe", link: "https://tryhackme.com/room/whyhackme", category: "Challenges" },
  { id: 72, title: "Brooklyn Nine Nine", link: "https://tryhackme.com/room/brooklynninenine", category: "Challenges" },
  { id: 73, title: "Magician", link: "https://tryhackme.com/room/magician", category: "Challenges" },
  { id: 74, title: "Ignite", link: "https://tryhackme.com/room/ignite", category: "Challenges" },
  { id: 75, title: "One Piece", link: "https://tryhackme.com/room/ctfonepiece65", category: "Challenges" },
  { id: 76, title: "Anonymous Playground", link: "https://tryhackme.com/room/anonymousplayground", category: "Challenges" },
  { id: 77, title: "You're in a cave", link: "https://tryhackme.com/room/inacave", category: "Challenges" },
  { id: 78, title: "Brute It", link: "https://tryhackme.com/room/bruteit", category: "Challenges" },
  { id: 79, title: "Wgel CTF", link: "https://tryhackme.com/room/wgelctf", category: "Challenges" },
  { id: 80, title: "Sakura Room", link: "https://tryhackme.com/room/sakura", category: "Challenges" },
  { id: 81, title: "Fowsniff CTF", link: "https://tryhackme.com/room/ctf", category: "Challenges" },
  { id: 82, title: "The Server from Hell", link: "https://tryhackme.com/room/theserverfromhell", category: "Challenges" },
  { id: 83, title: "Hijack", link: "https://tryhackme.com/room/hijack", category: "Challenges" },
  { id: 84, title: "BreakIt", link: "https://tryhackme.com/room/breakit", category: "Challenges" },
  { id: 85, title: "Searchlight - IMINT", link: "https://tryhackme.com/room/searchlightosint", category: "Challenges" },
  { id: 86, title: "h4cked", link: "https://tryhackme.com/room/h4cked", category: "Challenges" },
  { id: 87, title: "UltraTech", link: "https://tryhackme.com/room/ultratech1", category: "Challenges" },
  { id: 88, title: "Chocolate Factory", link: "https://tryhackme.com/room/chocolatefactory", category: "Challenges" },
  { id: 89, title: "JVM Reverse Engineering", link: "https://tryhackme.com/room/jvmreverseengineering", category: "Challenges" },
  { id: 90, title: "Boiler CTF", link: "https://tryhackme.com/room/boilerctf2", category: "Challenges" },
  { id: 91, title: "Disk Analysis & Autopsy", link: "https://tryhackme.com/room/autopsy2ze0", category: "Challenges" },
  { id: 92, title: "0day", link: "https://tryhackme.com/room/0day", category: "Challenges" },
  { id: 93, title: "Malware Reverse Engineering", link: "https://tryhackme.com/room/basicmalwarere", category: "Challenges" },
  { id: 94, title: "Inferno", link: "https://tryhackme.com/room/inferno", category: "Challenges" },
  { id: 95, title: "Billing", link: "https://tryhackme.com/room/billing", category: "Challenges" },
  { id: 96, title: "The Return of the Yeti", link: "https://tryhackme.com/room/adv3nt0fdbopsjcap", category: "Challenges" },
  { id: 97, title: "Blue", link: "https://tryhackme.com/room/blue", category: "Challenges" },
  { id: 98, title: "Oh My WebServer", link: "https://tryhackme.com/room/ohmyweb", category: "Challenges" },
  { id: 99, title: "SQHell", link: "https://tryhackme.com/room/sqhell", category: "Challenges" },
  { id: 100, title: "The Impossible Challenge", link: "https://tryhackme.com/room/theimpossiblechallenge", category: "Challenges" },
];
